<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 DNA descriptive statics - Part 1 | Computational Biology for All! Data science, bioinformatics, and other life-sciences awesomeness in R</title>
  <meta name="description" content="An entry-level text for computational biology" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 DNA descriptive statics - Part 1 | Computational Biology for All! Data science, bioinformatics, and other life-sciences awesomeness in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An entry-level text for computational biology" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 DNA descriptive statics - Part 1 | Computational Biology for All! Data science, bioinformatics, and other life-sciences awesomeness in R" />
  
  <meta name="twitter:description" content="An entry-level text for computational biology" />
  

<meta name="author" content="Nathan L. Brouwer" />


<meta name="date" content="2021-07-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="downloading-ncbi-sequence-data-by-hand.html"/>
<link rel="next" href="downloading-dna-sequences-with-r.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Computational Biology for All!</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="downloading-r.html"><a href="downloading-r.html"><i class="fa fa-check"></i><b>1</b> Downloading R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="downloading-r.html"><a href="downloading-r.html#preface-1"><i class="fa fa-check"></i><b>1.1</b> Preface</a></li>
<li class="chapter" data-level="1.2" data-path="downloading-r.html"><a href="downloading-r.html#introduction-to-r"><i class="fa fa-check"></i><b>1.2</b> Introduction to R</a></li>
<li class="chapter" data-level="1.3" data-path="downloading-r.html"><a href="downloading-r.html#installing-r"><i class="fa fa-check"></i><b>1.3</b> Installing R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="downloading-r.html"><a href="downloading-r.html#installing-r-on-a-windows-pc"><i class="fa fa-check"></i><b>1.3.1</b> Installing <em>R</em> on a Windows PC</a></li>
<li class="chapter" data-level="1.3.2" data-path="downloading-r.html"><a href="downloading-r.html#how-to-install-r-on-non-windows-computers-eg.-macintosh-or-linux-computers"><i class="fa fa-check"></i><b>1.3.2</b> How to install <em>R</em> on non-Windows computers (eg. Macintosh or Linux computers)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="downloading-r.html"><a href="downloading-r.html#starting-r"><i class="fa fa-check"></i><b>1.4</b> Starting <em>R</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="installing-the-rstudio-ide.html"><a href="installing-the-rstudio-ide.html"><i class="fa fa-check"></i><b>2</b> Installing the RStudio IDE</a>
<ul>
<li class="chapter" data-level="2.1" data-path="installing-the-rstudio-ide.html"><a href="installing-the-rstudio-ide.html#getting-to-know-rstudio"><i class="fa fa-check"></i><b>2.1</b> Getting to know RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="installing-the-rstudio-ide.html"><a href="installing-the-rstudio-ide.html#rstudio-versus-rstudio-cloud"><i class="fa fa-check"></i><b>2.2</b> RStudio versus RStudio Cloud</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="installing-r-packages.html"><a href="installing-r-packages.html"><i class="fa fa-check"></i><b>3</b> Installing <em>R</em> packages</a>
<ul>
<li class="chapter" data-level="3.1" data-path="installing-r-packages.html"><a href="installing-r-packages.html#downloading-packages-with-the-rstudio-ide"><i class="fa fa-check"></i><b>3.1</b> Downloading packages with the RStudio IDE</a></li>
<li class="chapter" data-level="3.2" data-path="installing-r-packages.html"><a href="installing-r-packages.html#downloading-packages-with-the-function-install.packages"><i class="fa fa-check"></i><b>3.2</b> Downloading packages with the function install.packages()</a></li>
<li class="chapter" data-level="3.3" data-path="installing-r-packages.html"><a href="installing-r-packages.html#using-packages-after-they-are-downloaded"><i class="fa fa-check"></i><b>3.3</b> Using packages after they are downloaded</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="installing-bioconductor.html"><a href="installing-bioconductor.html"><i class="fa fa-check"></i><b>4</b> Installing Bioconductor</a>
<ul>
<li class="chapter" data-level="4.1" data-path="installing-bioconductor.html"><a href="installing-bioconductor.html#bioconductor"><i class="fa fa-check"></i><b>4.1</b> Bioconductor</a></li>
<li class="chapter" data-level="4.2" data-path="installing-bioconductor.html"><a href="installing-bioconductor.html#installing-biocmanager"><i class="fa fa-check"></i><b>4.2</b> Installing BiocManager</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="a-brief-introduction-to-r.html"><a href="a-brief-introduction-to-r.html"><i class="fa fa-check"></i><b>5</b> A Brief introduction to R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="a-brief-introduction-to-r.html"><a href="a-brief-introduction-to-r.html#vocabulary"><i class="fa fa-check"></i><b>5.1</b> Vocabulary</a></li>
<li class="chapter" data-level="5.2" data-path="a-brief-introduction-to-r.html"><a href="a-brief-introduction-to-r.html#r-functions-etc"><i class="fa fa-check"></i><b>5.2</b> R functions etc</a></li>
<li class="chapter" data-level="5.3" data-path="a-brief-introduction-to-r.html"><a href="a-brief-introduction-to-r.html#a-brief-introduction-to-r-1"><i class="fa fa-check"></i><b>5.3</b> A brief introduction to R</a></li>
<li class="chapter" data-level="5.4" data-path="a-brief-introduction-to-r.html"><a href="a-brief-introduction-to-r.html#links-and-further-reading"><i class="fa fa-check"></i><b>5.4</b> Links and Further Reading</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="downloading-ncbi-sequence-data-by-hand.html"><a href="downloading-ncbi-sequence-data-by-hand.html"><i class="fa fa-check"></i><b>6</b> Downloading NCBI sequence data by hand</a>
<ul>
<li class="chapter" data-level="6.1" data-path="downloading-ncbi-sequence-data-by-hand.html"><a href="downloading-ncbi-sequence-data-by-hand.html#retrieving-genome-sequence-data-via-the-ncbi-website"><i class="fa fa-check"></i><b>6.1</b> Retrieving genome sequence data via the NCBI website</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html"><i class="fa fa-check"></i><b>7</b> DNA descriptive statics - Part 1</a>
<ul>
<li class="chapter" data-level="7.1" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#introduction"><i class="fa fa-check"></i><b>7.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#note-on-the-biology-in-this-section"><i class="fa fa-check"></i><b>7.1.1</b> Note on the biology in this section</a></li>
<li class="chapter" data-level="7.1.2" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#vocabulary-1"><i class="fa fa-check"></i><b>7.1.2</b> Vocabulary</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#preliminaries"><i class="fa fa-check"></i><b>7.2</b> Preliminaries</a></li>
<li class="chapter" data-level="7.3" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#converting-dna-from-fasta-format"><i class="fa fa-check"></i><b>7.3</b> Converting DNA from FASTA format</a></li>
<li class="chapter" data-level="7.4" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#length-of-a-dna-sequence"><i class="fa fa-check"></i><b>7.4</b> Length of a DNA sequence</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#base-composition-of-a-dna-sequence"><i class="fa fa-check"></i><b>7.4.1</b> Base composition of a DNA sequence</a></li>
<li class="chapter" data-level="7.4.2" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#gc-content-of-dna"><i class="fa fa-check"></i><b>7.4.2</b> GC Content of DNA</a></li>
<li class="chapter" data-level="7.4.3" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#dna-words"><i class="fa fa-check"></i><b>7.4.3</b> DNA words</a></li>
<li class="chapter" data-level="7.4.4" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#summary"><i class="fa fa-check"></i><b>7.4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#acknowledgements"><i class="fa fa-check"></i><b>7.5</b> Acknowledgements</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#license"><i class="fa fa-check"></i><b>7.5.1</b> License</a></li>
<li class="chapter" data-level="7.5.2" data-path="dna-descriptive-statics-part-1.html"><a href="dna-descriptive-statics-part-1.html#exercises"><i class="fa fa-check"></i><b>7.5.2</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html"><i class="fa fa-check"></i><b>8</b> Downloading DNA sequences with R</a>
<ul>
<li class="chapter" data-level="8.0.1" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#functions"><i class="fa fa-check"></i><b>8.0.1</b> Functions</a></li>
<li class="chapter" data-level="8.0.2" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#softwarewebsites"><i class="fa fa-check"></i><b>8.0.2</b> Software/websites</a></li>
<li class="chapter" data-level="8.0.3" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#r-vocabulary"><i class="fa fa-check"></i><b>8.0.3</b> R vocabulary</a></li>
<li class="chapter" data-level="8.0.4" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#file-types"><i class="fa fa-check"></i><b>8.0.4</b> File types</a></li>
<li class="chapter" data-level="8.0.5" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#bioinformatics-vocabulary"><i class="fa fa-check"></i><b>8.0.5</b> Bioinformatics vocabulary</a></li>
<li class="chapter" data-level="8.0.6" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#organisms-and-sequence-accessions"><i class="fa fa-check"></i><b>8.0.6</b> Organisms and Sequence accessions</a></li>
<li class="chapter" data-level="8.0.7" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#preliminaries-1"><i class="fa fa-check"></i><b>8.0.7</b> Preliminaries</a></li>
<li class="chapter" data-level="8.1" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#dna-sequence-statistics-part-1"><i class="fa fa-check"></i><b>8.1</b> DNA Sequence Statistics: Part 1</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#using-r-for-bioinformatics"><i class="fa fa-check"></i><b>8.1.1</b> Using R for Bioinformatics</a></li>
<li class="chapter" data-level="8.1.2" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#r-packages-for-bioinformatics-bioconductor-and-seqinr"><i class="fa fa-check"></i><b>8.1.2</b> R packages for bioinformatics: Bioconductor and SeqinR</a></li>
<li class="chapter" data-level="8.1.3" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#fasta-file-format"><i class="fa fa-check"></i><b>8.1.3</b> FASTA file format</a></li>
<li class="chapter" data-level="8.1.4" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#the-ncbi-sequence-database"><i class="fa fa-check"></i><b>8.1.4</b> The NCBI sequence database</a></li>
<li class="chapter" data-level="8.1.5" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#retrieving-genome-sequence-data-using-rentrez"><i class="fa fa-check"></i><b>8.1.5</b> Retrieving genome sequence data using rentrez</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#convert-fasta-sequence-to-an-r-variable"><i class="fa fa-check"></i><b>8.2</b> Convert FASTA sequence to an R variable</a></li>
<li class="chapter" data-level="8.3" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#saving-fasta-files"><i class="fa fa-check"></i><b>8.3</b> Saving FASTA files</a></li>
<li class="chapter" data-level="8.4" data-path="downloading-dna-sequences-with-r.html"><a href="downloading-dna-sequences-with-r.html#reading-in-fasta-files"><i class="fa fa-check"></i><b>8.4</b> Reading in FASTA files</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html"><i class="fa fa-check"></i><b>9</b> Introduction to biological sequences databases</a>
<ul>
<li class="chapter" data-level="9.1" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#to-do"><i class="fa fa-check"></i><b>9.1</b> To do</a></li>
<li class="chapter" data-level="9.2" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#biological-sequence-databases"><i class="fa fa-check"></i><b>9.2</b> Biological sequence databases</a></li>
<li class="chapter" data-level="9.3" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#the-ncbi-sequence-database-1"><i class="fa fa-check"></i><b>9.3</b> The NCBI Sequence Database</a></li>
<li class="chapter" data-level="9.4" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#the-ncbi-sub-databases"><i class="fa fa-check"></i><b>9.4</b> The NCBI Sub-Databases</a></li>
<li class="chapter" data-level="9.5" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#ncbi-genbank-record-format"><i class="fa fa-check"></i><b>9.5</b> NCBI GenBank Record Format</a></li>
<li class="chapter" data-level="9.6" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#the-fasta-file-format"><i class="fa fa-check"></i><b>9.6</b> The FASTA file format</a></li>
<li class="chapter" data-level="9.7" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#graphics"><i class="fa fa-check"></i><b>9.7</b> Graphics</a></li>
<li class="chapter" data-level="9.8" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#refseq"><i class="fa fa-check"></i><b>9.8</b> RefSeq</a></li>
<li class="chapter" data-level="9.9" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#querying-the-ncbi-database"><i class="fa fa-check"></i><b>9.9</b> Querying the NCBI Database</a></li>
<li class="chapter" data-level="9.10" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#querying-the-ncbi-database-via-the-ncbi-website-for-reference"><i class="fa fa-check"></i><b>9.10</b> Querying the NCBI Database via the NCBI Website (for reference)</a></li>
<li class="chapter" data-level="9.11" data-path="introduction-to-biological-sequences-databases.html"><a href="introduction-to-biological-sequences-databases.html#example-finding-the-sequences-published-in-nature-460352-358-for-reference"><i class="fa fa-check"></i><b>9.11</b> Example: finding the sequences published in Nature 460:352-358 (for reference)</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="programming-in-r-for-loops-and-functions.html"><a href="programming-in-r-for-loops-and-functions.html"><i class="fa fa-check"></i><b>10</b> Programming in R: for loops and functions</a>
<ul>
<li class="chapter" data-level="10.1" data-path="programming-in-r-for-loops-and-functions.html"><a href="programming-in-r-for-loops-and-functions.html#vocab"><i class="fa fa-check"></i><b>10.1</b> Vocab</a></li>
<li class="chapter" data-level="10.2" data-path="programming-in-r-for-loops-and-functions.html"><a href="programming-in-r-for-loops-and-functions.html#basic-programming-in-r"><i class="fa fa-check"></i><b>10.2</b> Basic programming in R</a></li>
<li class="chapter" data-level="10.3" data-path="programming-in-r-for-loops-and-functions.html"><a href="programming-in-r-for-loops-and-functions.html#functions-in-r"><i class="fa fa-check"></i><b>10.3</b> Functions in R</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html"><i class="fa fa-check"></i><b>11</b> Mini tutorial: Vectors in R</a>
<ul>
<li class="chapter" data-level="11.1" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#vocab-and-functions"><i class="fa fa-check"></i><b>11.1</b> Vocab and functions</a></li>
<li class="chapter" data-level="11.2" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#vectors-in-r"><i class="fa fa-check"></i><b>11.2</b> Vectors in R</a></li>
<li class="chapter" data-level="11.3" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#math-on-vectors"><i class="fa fa-check"></i><b>11.3</b> Math on vectors</a></li>
<li class="chapter" data-level="11.4" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#functions-on-vectors"><i class="fa fa-check"></i><b>11.4</b> Functions on vectors</a></li>
<li class="chapter" data-level="11.5" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#operations-with-two-vectors"><i class="fa fa-check"></i><b>11.5</b> Operations with two vectors</a></li>
<li class="chapter" data-level="11.6" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#subsetting-vectors"><i class="fa fa-check"></i><b>11.6</b> Subsetting vectors</a></li>
<li class="chapter" data-level="11.7" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#sequences-of-numbers"><i class="fa fa-check"></i><b>11.7</b> Sequences of numbers</a></li>
<li class="chapter" data-level="11.8" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#vectors-can-hold-numeric-or-character-data"><i class="fa fa-check"></i><b>11.8</b> Vectors can hold numeric or character data</a></li>
<li class="chapter" data-level="11.9" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#regular-expressions-can-modify-character-data"><i class="fa fa-check"></i><b>11.9</b> Regular expressions can modify character data</a></li>
<li class="chapter" data-level="11.10" data-path="mini-tutorial-vectors-in-r.html"><a href="mini-tutorial-vectors-in-r.html#plotting-vectors-in-base-r"><i class="fa fa-check"></i><b>11.10</b> Plotting vectors in base R</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="note-please-save-this-file-with-a-new-file-name-to-your-documents-folder-or-desktop.html"><a href="note-please-save-this-file-with-a-new-file-name-to-your-documents-folder-or-desktop.html"><i class="fa fa-check"></i><b>12</b> NOTE: please save this file with a new file name to your documents folder or desktop</a></li>
<li class="chapter" data-level="13" data-path="downloading-sequences-from-uniprot-by-hand.html"><a href="downloading-sequences-from-uniprot-by-hand.html"><i class="fa fa-check"></i><b>13</b> Downloading sequences from UniProt by hand</a>
<ul>
<li class="chapter" data-level="13.1" data-path="downloading-sequences-from-uniprot-by-hand.html"><a href="downloading-sequences-from-uniprot-by-hand.html#vocab-1"><i class="fa fa-check"></i><b>13.1</b> Vocab</a></li>
<li class="chapter" data-level="13.2" data-path="downloading-sequences-from-uniprot-by-hand.html"><a href="downloading-sequences-from-uniprot-by-hand.html#uniprot"><i class="fa fa-check"></i><b>13.2</b> UniProt</a></li>
<li class="chapter" data-level="13.3" data-path="downloading-sequences-from-uniprot-by-hand.html"><a href="downloading-sequences-from-uniprot-by-hand.html#viewing-the-uniprot-webpage-for-a-protein-sequence"><i class="fa fa-check"></i><b>13.3</b> Viewing the UniProt webpage for a protein sequence</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="downloading-sequences-from-uniprot-by-hand.html"><a href="downloading-sequences-from-uniprot-by-hand.html#protein-function"><i class="fa fa-check"></i><b>13.3.1</b> Protein function</a></li>
<li class="chapter" data-level="13.3.2" data-path="downloading-sequences-from-uniprot-by-hand.html"><a href="downloading-sequences-from-uniprot-by-hand.html#protein-sequence-and-size"><i class="fa fa-check"></i><b>13.3.2</b> Protein sequence and size</a></li>
<li class="chapter" data-level="13.3.3" data-path="downloading-sequences-from-uniprot-by-hand.html"><a href="downloading-sequences-from-uniprot-by-hand.html#other-information"><i class="fa fa-check"></i><b>13.3.3</b> Other information</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="downloading-sequences-from-uniprot-by-hand.html"><a href="downloading-sequences-from-uniprot-by-hand.html#retrieving-a-uniprot-protein-sequence-via-the-uniprot-website"><i class="fa fa-check"></i><b>13.4</b> Retrieving a UniProt protein sequence via the UniProt website</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="sequence-databases.html"><a href="sequence-databases.html"><i class="fa fa-check"></i><b>14</b> Sequence Databases</a>
<ul>
<li class="chapter" data-level="14.1" data-path="sequence-databases.html"><a href="sequence-databases.html#querying-the-ncbi-database-via-r"><i class="fa fa-check"></i><b>14.1</b> Querying the NCBI Database via R</a></li>
<li class="chapter" data-level="14.2" data-path="sequence-databases.html"><a href="sequence-databases.html#summary-1"><i class="fa fa-check"></i><b>14.2</b> Summary</a></li>
<li class="chapter" data-level="14.3" data-path="sequence-databases.html"><a href="sequence-databases.html#acknowledgements-1"><i class="fa fa-check"></i><b>14.3</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html"><i class="fa fa-check"></i><b>15</b> Local variation in GC content</a>
<ul>
<li class="chapter" data-level="15.0.1" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#note-on-the-biology-in-this-section-1"><i class="fa fa-check"></i><b>15.0.1</b> Note on the biology in this section</a></li>
<li class="chapter" data-level="15.1" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#vocabulary-2"><i class="fa fa-check"></i><b>15.1</b> Vocabulary</a></li>
<li class="chapter" data-level="15.2" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#reading-sequence-data-with-rentrezentrez_fetch"><i class="fa fa-check"></i><b>15.2</b> Reading sequence data with rentrez::entrez_fetch</a></li>
<li class="chapter" data-level="15.3" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#local-variation-in-gc-content-1"><i class="fa fa-check"></i><b>15.3</b> Local variation in GC content</a></li>
<li class="chapter" data-level="15.4" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#a-sliding-window-analysis-of-gc-content"><i class="fa fa-check"></i><b>15.4</b> A sliding window analysis of GC content</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#over-represented-and-under-represented-dna-words"><i class="fa fa-check"></i><b>15.4.1</b> Over-represented and under-represented DNA words</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#summary-2"><i class="fa fa-check"></i><b>15.5</b> Summary</a></li>
<li class="chapter" data-level="15.6" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#further-reading"><i class="fa fa-check"></i><b>15.6</b> Further Reading</a></li>
<li class="chapter" data-level="15.7" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#acknowledgements-2"><i class="fa fa-check"></i><b>15.7</b> Acknowledgements</a>
<ul>
<li class="chapter" data-level="15.7.1" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#license-1"><i class="fa fa-check"></i><b>15.7.1</b> License</a></li>
</ul></li>
<li class="chapter" data-level="15.8" data-path="local-variation-in-gc-content.html"><a href="local-variation-in-gc-content.html#exercises-1"><i class="fa fa-check"></i><b>15.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="aligments-in-r.html"><a href="aligments-in-r.html"><i class="fa fa-check"></i><b>16</b> Aligments in R</a>
<ul>
<li class="chapter" data-level="16.1" data-path="aligments-in-r.html"><a href="aligments-in-r.html#retrieving-a-uniprot-protein-sequence-using-seqinr"><i class="fa fa-check"></i><b>16.1</b> Retrieving a UniProt protein sequence using SeqinR</a></li>
<li class="chapter" data-level="16.2" data-path="aligments-in-r.html"><a href="aligments-in-r.html#comparing-two-sequences-using-a-dotplot"><i class="fa fa-check"></i><b>16.2</b> Comparing two sequences using a dotplot</a></li>
<li class="chapter" data-level="16.3" data-path="aligments-in-r.html"><a href="aligments-in-r.html#aligning-uniprot-sequences"><i class="fa fa-check"></i><b>16.3</b> Aligning UniProt sequences</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="retrieving-multiple-sequences-in-r.html"><a href="retrieving-multiple-sequences-in-r.html"><i class="fa fa-check"></i><b>17</b> Retrieving multiple sequences in R</a>
<ul>
<li class="chapter" data-level="17.1" data-path="retrieving-multiple-sequences-in-r.html"><a href="retrieving-multiple-sequences-in-r.html#prelminaries"><i class="fa fa-check"></i><b>17.1</b> Prelminaries</a></li>
<li class="chapter" data-level="17.2" data-path="retrieving-multiple-sequences-in-r.html"><a href="retrieving-multiple-sequences-in-r.html#retrieving-a-list-of-sequences-from-uniprot"><i class="fa fa-check"></i><b>17.2</b> Retrieving a list of sequences from UniProt</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="multiple-alignment-with-clustal.html"><a href="multiple-alignment-with-clustal.html"><i class="fa fa-check"></i><b>18</b> Multiple alignment with Clustal</a>
<ul>
<li class="chapter" data-level="18.1" data-path="multiple-alignment-with-clustal.html"><a href="multiple-alignment-with-clustal.html#installing-the-clustal-multiple-alignment-software"><i class="fa fa-check"></i><b>18.1</b> Installing the CLUSTAL multiple alignment software</a></li>
<li class="chapter" data-level="18.2" data-path="multiple-alignment-with-clustal.html"><a href="multiple-alignment-with-clustal.html#discarding-very-poorly-conserved-regions-from-an-alignment"><i class="fa fa-check"></i><b>18.2</b> Discarding very poorly conserved regions from an alignment</a></li>
<li class="chapter" data-level="18.3" data-path="multiple-alignment-with-clustal.html"><a href="multiple-alignment-with-clustal.html#calculating-genetic-distances-between-protein-sequences"><i class="fa fa-check"></i><b>18.3</b> Calculating genetic distances between protein sequences</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="rooted-neighbor-joining-phylogenetic-trees.html"><a href="rooted-neighbor-joining-phylogenetic-trees.html"><i class="fa fa-check"></i><b>19</b> Rooted Neighbor-joining Phylogenetic trees</a>
<ul>
<li class="chapter" data-level="19.1" data-path="rooted-neighbor-joining-phylogenetic-trees.html"><a href="rooted-neighbor-joining-phylogenetic-trees.html#building-a-rooted-phylogenetic-tree-for-protein-sequences"><i class="fa fa-check"></i><b>19.1</b> Building a rooted phylogenetic tree for protein sequences</a></li>
<li class="chapter" data-level="19.2" data-path="rooted-neighbor-joining-phylogenetic-trees.html"><a href="rooted-neighbor-joining-phylogenetic-trees.html#building-a-phylogenetic-tree-for-dna-or-mrna-sequences"><i class="fa fa-check"></i><b>19.2</b> Building a phylogenetic tree for DNA or mRNA sequences</a></li>
<li class="chapter" data-level="19.3" data-path="rooted-neighbor-joining-phylogenetic-trees.html"><a href="rooted-neighbor-joining-phylogenetic-trees.html#summary-3"><i class="fa fa-check"></i><b>19.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="unrooted-neighbor-joining-phylogenetic-trees.html"><a href="unrooted-neighbor-joining-phylogenetic-trees.html"><i class="fa fa-check"></i><b>20</b> Unrooted Neighbor-joining Phylogenetic trees</a>
<ul>
<li class="chapter" data-level="20.1" data-path="unrooted-neighbor-joining-phylogenetic-trees.html"><a href="unrooted-neighbor-joining-phylogenetic-trees.html#building-an-unrooted-phylogenetic-tree-for-protein-sequences"><i class="fa fa-check"></i><b>20.1</b> Building an unrooted phylogenetic tree for protein sequences</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="testing-the-significance-of-an-alignment.html"><a href="testing-the-significance-of-an-alignment.html"><i class="fa fa-check"></i><b>21</b> Testing the significance of an alignment</a>
<ul>
<li class="chapter" data-level="21.1" data-path="testing-the-significance-of-an-alignment.html"><a href="testing-the-significance-of-an-alignment.html#calculating-the-statistical-significance-of-a-pairwise-global-alignment"><i class="fa fa-check"></i><b>21.1</b> Calculating the statistical significance of a pairwise global alignment</a></li>
<li class="chapter" data-level="21.2" data-path="testing-the-significance-of-an-alignment.html"><a href="testing-the-significance-of-an-alignment.html#summary-4"><i class="fa fa-check"></i><b>21.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="computational-gene-finding.html"><a href="computational-gene-finding.html"><i class="fa fa-check"></i><b>22</b> Computational gene finding</a>
<ul>
<li class="chapter" data-level="22.1" data-path="computational-gene-finding.html"><a href="computational-gene-finding.html#the-genetic-code"><i class="fa fa-check"></i><b>22.1</b> The genetic code</a></li>
<li class="chapter" data-level="22.2" data-path="computational-gene-finding.html"><a href="computational-gene-finding.html#reading-frames"><i class="fa fa-check"></i><b>22.2</b> Reading frames</a></li>
<li class="chapter" data-level="22.3" data-path="computational-gene-finding.html"><a href="computational-gene-finding.html#finding-open-reading-frames-on-the-forward-strand-of-a-dna-sequence"><i class="fa fa-check"></i><b>22.3</b> Finding open reading frames on the forward strand of a DNA sequence</a></li>
<li class="chapter" data-level="22.4" data-path="computational-gene-finding.html"><a href="computational-gene-finding.html#lengths-of-open-reading-frames"><i class="fa fa-check"></i><b>22.4</b> Lengths of open reading frames</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="significance-of-orfs.html"><a href="significance-of-orfs.html"><i class="fa fa-check"></i><b>23</b> Significance of ORFs</a>
<ul>
<li class="chapter" data-level="23.1" data-path="significance-of-orfs.html"><a href="significance-of-orfs.html#identifying-significant-open-reading-frames"><i class="fa fa-check"></i><b>23.1</b> Identifying significant open reading frames</a></li>
<li class="chapter" data-level="23.2" data-path="significance-of-orfs.html"><a href="significance-of-orfs.html#summary-5"><i class="fa fa-check"></i><b>23.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="comparative-genomics.html"><a href="comparative-genomics.html"><i class="fa fa-check"></i><b>24</b> Comparative Genomics</a></li>
<li class="chapter" data-level="25" data-path="introduction-1.html"><a href="introduction-1.html"><i class="fa fa-check"></i><b>25</b> Introduction</a></li>
<li class="chapter" data-level="26" data-path="using-the-biomart-r-library-to-query-the-ensembl-database.html"><a href="using-the-biomart-r-library-to-query-the-ensembl-database.html"><i class="fa fa-check"></i><b>26</b> Using the biomaRt R Library to Query the Ensembl Database</a></li>
<li class="chapter" data-level="27" data-path="comparing-the-number-of-genes-in-two-species.html"><a href="comparing-the-number-of-genes-in-two-species.html"><i class="fa fa-check"></i><b>27</b> Comparing the number of genes in two species</a></li>
<li class="chapter" data-level="28" data-path="identifying-homologous-genes-between-two-species.html"><a href="identifying-homologous-genes-between-two-species.html"><i class="fa fa-check"></i><b>28</b> Identifying homologous genes between two species</a></li>
<li class="chapter" data-level="29" data-path="summary-6.html"><a href="summary-6.html"><i class="fa fa-check"></i><b>29</b> Summary</a></li>
<li class="chapter" data-level="30" data-path="links-and-further-reading-1.html"><a href="links-and-further-reading-1.html"><i class="fa fa-check"></i><b>30</b> Links and Further Reading</a></li>
<li class="chapter" data-level="31" data-path="acknowledgements-3.html"><a href="acknowledgements-3.html"><i class="fa fa-check"></i><b>31</b> Acknowledgements</a></li>
<li class="chapter" data-level="32" data-path="contact.html"><a href="contact.html"><i class="fa fa-check"></i><b>32</b> Contact</a></li>
<li class="chapter" data-level="33" data-path="license-2.html"><a href="license-2.html"><i class="fa fa-check"></i><b>33</b> License</a></li>
<li class="chapter" data-level="34" data-path="exercises-2.html"><a href="exercises-2.html"><i class="fa fa-check"></i><b>34</b> Exercises</a></li>
<li class="chapter" data-level="35" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html"><i class="fa fa-check"></i><b>35</b> Hidden Markov Models</a>
<ul>
<li class="chapter" data-level="35.1" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#r-programming-101-initializing-vectors"><i class="fa fa-check"></i><b>35.1</b> R Programming 101: Initializing vectors</a></li>
<li class="chapter" data-level="35.2" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#a-multinomial-model-of-dna-sequence-evolution"><i class="fa fa-check"></i><b>35.2</b> A multinomial model of DNA sequence evolution</a></li>
<li class="chapter" data-level="35.3" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#generating-a-dna-sequence-using-a-multinomial-model"><i class="fa fa-check"></i><b>35.3</b> Generating a DNA sequence using a multinomial model</a></li>
<li class="chapter" data-level="35.4" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#a-markov-model-of-dna-sequence-evolution"><i class="fa fa-check"></i><b>35.4</b> A Markov model of DNA sequence evolution</a></li>
<li class="chapter" data-level="35.5" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#the-transition-matrix-for-a-markov-model"><i class="fa fa-check"></i><b>35.5</b> The transition matrix for a Markov model</a></li>
<li class="chapter" data-level="35.6" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#generating-a-dna-sequence-using-a-markov-model"><i class="fa fa-check"></i><b>35.6</b> Generating a DNA sequence using a Markov model</a></li>
<li class="chapter" data-level="35.7" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#a-hidden-markov-model-of-dna-sequence-evolution"><i class="fa fa-check"></i><b>35.7</b> A Hidden Markov Model of DNA sequence evolution</a></li>
<li class="chapter" data-level="35.8" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#the-transition-matrix-and-emission-matrix-for-a-hmm"><i class="fa fa-check"></i><b>35.8</b> The transition matrix and emission matrix for a HMM</a></li>
<li class="chapter" data-level="35.9" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#generating-a-dna-sequence-using-a-hmm"><i class="fa fa-check"></i><b>35.9</b> Generating a DNA sequence using a HMM</a></li>
<li class="chapter" data-level="35.10" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#inferring-the-states-of-a-hmm-that-generated-a-dna-sequence"><i class="fa fa-check"></i><b>35.10</b> Inferring the states of a HMM that generated a DNA sequence</a></li>
<li class="chapter" data-level="35.11" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#a-hidden-markov-model-of-protein-sequence-evolution"><i class="fa fa-check"></i><b>35.11</b> A Hidden Markov Model of protein sequence evolution</a></li>
<li class="chapter" data-level="35.12" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#summary-7"><i class="fa fa-check"></i><b>35.12</b> Summary</a></li>
<li class="chapter" data-level="35.13" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#links-and-further-reading-2"><i class="fa fa-check"></i><b>35.13</b> Links and Further Reading</a></li>
<li class="chapter" data-level="35.14" data-path="hidden-markov-models.html"><a href="hidden-markov-models.html#exercises-3"><i class="fa fa-check"></i><b>35.14</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#part-appendices"><i class="fa fa-check"></i>(PART) Appendices</a>
<ul>
<li><a href="#section"></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-01-getting-access-to-r.html"><a href="appendix-01-getting-access-to-r.html"><i class="fa fa-check"></i>Appendix 01: Getting access to R</a>
<ul>
<li class="chapter" data-level="35.15" data-path="appendix-01-getting-access-to-r.html"><a href="appendix-01-getting-access-to-r.html#getting-started-with-r-and-rstudio"><i class="fa fa-check"></i><b>35.15</b> Getting Started With R and RStudio</a>
<ul>
<li class="chapter" data-level="35.15.1" data-path="appendix-01-getting-access-to-r.html"><a href="appendix-01-getting-access-to-r.html#rstudio-cloud"><i class="fa fa-check"></i><b>35.15.1</b> RStudio Cloud</a></li>
<li class="chapter" data-level="35.15.2" data-path="appendix-01-getting-access-to-r.html"><a href="appendix-01-getting-access-to-r.html#getting-r-onto-your-own-computer"><i class="fa fa-check"></i><b>35.15.2</b> Getting R onto your own computer</a></li>
<li class="chapter" data-level="35.15.3" data-path="appendix-01-getting-access-to-r.html"><a href="appendix-01-getting-access-to-r.html#getting-rstudio-onto-your-computer"><i class="fa fa-check"></i><b>35.15.3</b> Getting RStudio onto your computer</a></li>
<li class="chapter" data-level="35.15.4" data-path="appendix-01-getting-access-to-r.html"><a href="appendix-01-getting-access-to-r.html#keep-r-and-rstudio-current"><i class="fa fa-check"></i><b>35.15.4</b> Keep R and RStudio current</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html"><i class="fa fa-check"></i>Getting started with R itself (or not)</a>
<ul>
<li class="chapter" data-level="" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#vocabulary-3"><i class="fa fa-check"></i>Vocabulary</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#r-commands"><i class="fa fa-check"></i>R commands</a></li>
<li class="chapter" data-level="35.16" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#help"><i class="fa fa-check"></i><b>35.16</b> Help!</a>
<ul>
<li class="chapter" data-level="35.16.1" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#getting-help-from-r"><i class="fa fa-check"></i><b>35.16.1</b> Getting “help” from R</a></li>
<li class="chapter" data-level="35.16.2" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#getting-help-from-the-internet"><i class="fa fa-check"></i><b>35.16.2</b> Getting help from the internet</a></li>
<li class="chapter" data-level="35.16.3" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#getting-help-from-online-forums"><i class="fa fa-check"></i><b>35.16.3</b> Getting help from online forums</a></li>
<li class="chapter" data-level="35.16.4" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#getting-help-from-twitter"><i class="fa fa-check"></i><b>35.16.4</b> Getting help from twitter</a></li>
</ul></li>
<li class="chapter" data-level="35.17" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#other-features-of-rstudio"><i class="fa fa-check"></i><b>35.17</b> Other features of RStudio</a>
<ul>
<li class="chapter" data-level="35.17.1" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#ajusting-pane-the-layout"><i class="fa fa-check"></i><b>35.17.1</b> Ajusting pane the layout</a></li>
<li class="chapter" data-level="35.17.2" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#adjusting-size-of-windows"><i class="fa fa-check"></i><b>35.17.2</b> Adjusting size of windows</a></li>
</ul></li>
<li class="chapter" data-level="35.18" data-path="getting-started-with-r-itself-or-not.html"><a href="getting-started-with-r-itself-or-not.html#practice-optional"><i class="fa fa-check"></i><b>35.18</b> Practice (OPTIONAL)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Computational Biology for All! Data science, bioinformatics, and other life-sciences awesomeness in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="dna-descriptive-statics---part-1" class="section level1" number="7">
<h1><span class="header-section-number">Chapter 7</span> DNA descriptive statics - Part 1</h1>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="dna-descriptive-statics-part-1.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(compbio4all)</span></code></pre></div>
<div id="introduction" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Introduction</h2>
<div id="note-on-the-biology-in-this-section" class="section level3" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Note on the biology in this section</h3>
<p>Some of the biology in this tutorial appears to be out of date. Specifically, research on the biological basis of unusual frequencies of DNA “words” does not appear to be much current interest in bioinformatics and genomics. (In contrast, methylation of bases within certain DNA words is being worked on.) The examples are still good for practicing R skills.</p>
</div>
<div id="vocabulary-1" class="section level3" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Vocabulary</h3>
<p>GC content
DNA words</p>
<p>scatterplots, histograms, piecharts, and boxplots</p>
<p>seqinr::GC()
seqinr::count()</p>
</div>
</div>
<div id="preliminaries" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Preliminaries</h2>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="dna-descriptive-statics-part-1.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(seqinr)</span></code></pre></div>
</div>
<div id="converting-dna-from-fasta-format" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Converting DNA from FASTA format</h2>
<p>In a previous exercise we downloaded and examined DNA sequence in the FASTA format. The sequence we worked with is actually stored as a data file within this package and can be brought into memory using the data() command</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="dna-descriptive-statics-part-1.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;dengueseq_fasta&quot;</span>)</span></code></pre></div>
<p>We can look at this with the str() command</p>
<p>This isn’t in a format we can actually work with so we’ll use the function fasta_cleaner()</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="dna-descriptive-statics-part-1.html#cb55-1" aria-hidden="true" tabindex="-1"></a>header. <span class="ot">&lt;-</span> <span class="st">&quot;&gt;NC_001477.1 Dengue virus 1, complete genome&quot;</span></span>
<span id="cb55-2"><a href="dna-descriptive-statics-part-1.html#cb55-2" aria-hidden="true" tabindex="-1"></a>dengueseq_vector <span class="ot">&lt;-</span> compbio4all<span class="sc">::</span><span class="fu">fasta_cleaner</span>(dengueseq_fasta)</span></code></pre></div>
<p>Now check it out.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="dna-descriptive-statics-part-1.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dengueseq_vector)</span></code></pre></div>
<pre><code>##  chr [1:10735] &quot;A&quot; &quot;G&quot; &quot;T&quot; &quot;T&quot; &quot;G&quot; &quot;T&quot; &quot;T&quot; &quot;A&quot; &quot;G&quot; &quot;T&quot; &quot;C&quot; &quot;T&quot; &quot;A&quot; &quot;C&quot; &quot;G&quot; ...</code></pre>
<p>What we have here is each base of the sequence in a seperate slot of our vector.</p>
<p>The first four bases are “AGTT”</p>
<p>We can see the first one like this</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="dna-descriptive-statics-part-1.html#cb58-1" aria-hidden="true" tabindex="-1"></a>dengueseq_vector[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] &quot;A&quot;</code></pre>
<p>The second one like this</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="dna-descriptive-statics-part-1.html#cb60-1" aria-hidden="true" tabindex="-1"></a>dengueseq_vector[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] &quot;G&quot;</code></pre>
<p>The first and second like this</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="dna-descriptive-statics-part-1.html#cb62-1" aria-hidden="true" tabindex="-1"></a>dengueseq_vector[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;G&quot;</code></pre>
<p>and all four like this</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="dna-descriptive-statics-part-1.html#cb64-1" aria-hidden="true" tabindex="-1"></a>dengueseq_vector[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;G&quot; &quot;T&quot; &quot;T&quot;</code></pre>
</div>
<div id="length-of-a-dna-sequence" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> Length of a DNA sequence</h2>
<p>Once you have retrieved a DNA sequence, we can obtain some simple statistics to describe that sequence, such as the sequence’s total length in nucleotides. In the above example, we retrieved the DEN-1 Dengue virus genome sequence, and stored it in the vector variable dengueseq_vector To obtain the length of the genome sequence, we would use the length() function, typing:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="dna-descriptive-statics-part-1.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(dengueseq_vector)</span></code></pre></div>
<pre><code>## [1] 10735</code></pre>
<p>The length() function will give you back the length of the sequence stored in variable dengueseq_vector, in nucleotides. The length() function actually gives the number of <strong>elements</strong> (slots) in the input vector that you passed to it, which in this case in the number of elements in the vector dengueseq_vector. Since each element of the vector dengueseq_vector contains one nucleotide of the DEN-1 Dengue virus sequence, the result for the DEN-1 Dengue virus genome tells us the length of its genome sequence (ie. 10735 nucleotides long).</p>
<div id="base-composition-of-a-dna-sequence" class="section level3" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Base composition of a DNA sequence</h3>
<p>An obvious first analysis of any DNA sequence is to count the number of occurrences of the four different nucleotides (“A,” “C,” “G,” and “T”) in the sequence. This can be done using the the table() function. For example, to find the number of As, Cs, Gs, and Ts in the DEN-1 Dengue virus sequence (which you have put into vector variable dengueseq_vector, using the commands above), you would type:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="dna-descriptive-statics-part-1.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(dengueseq_vector)</span></code></pre></div>
<pre><code>## dengueseq_vector
##    A    C    G    T 
## 3426 2240 2770 2299</code></pre>
<p>This means that the DEN-1 Dengue virus genome sequence has 3426 As occurring throughout the genome, 2240 Cs, and so forth.</p>
</div>
<div id="gc-content-of-dna" class="section level3" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> GC Content of DNA</h3>
<p>One of the most fundamental properties of a genome sequence is its <strong>GC content</strong>, the fraction of the sequence that consists of Gs and Cs, ie. the %(G+C).</p>
<p>The GC content can be calculated as the percentage of the bases in the genome that are Gs or Cs. That is, GC content = (number of Gs + number of Cs)<em>100/(genome length). For example, if the genome is 100 bp, and 20 bases are Gs and 21 bases are Cs, then the GC content is (20 + 21)</em>100/100 = 41%.</p>
<p>You can easily calculate the GC content based on the number of As, Gs, Cs, and Ts in the genome sequence. For example, for the DEN-1 Dengue virus genome sequence, we know from using the table() function above that the genome contains 3426 As, 2240 Cs, 2770 Gs and 2299 Ts. Therefore, we can calculate the GC content using the command:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="dna-descriptive-statics-part-1.html#cb70-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">2240</span><span class="sc">+</span><span class="dv">2770</span>)<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span>(<span class="dv">3426</span><span class="sc">+</span><span class="dv">2240</span><span class="sc">+</span><span class="dv">2770</span><span class="sc">+</span><span class="dv">2299</span>)</span></code></pre></div>
<pre><code>## [1] 46.66977</code></pre>
<p>Alternatively, if you are feeling lazy, you can use the GC() function in the SeqinR package, which gives the fraction of bases in the sequence that are Gs or Cs.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="dna-descriptive-statics-part-1.html#cb72-1" aria-hidden="true" tabindex="-1"></a>seqinr<span class="sc">::</span><span class="fu">GC</span>(dengueseq_vector)</span></code></pre></div>
<pre><code>## [1] 0.4666977</code></pre>
<p>The result above means that the fraction of bases in the DEN-1 Dengue virus genome that are Gs or Cs is 0.4666977. To convert the fraction to a percentage, we have to multiply by 100, so the GC content as a percentage is 46.66977%.</p>
</div>
<div id="dna-words" class="section level3" number="7.4.3">
<h3><span class="header-section-number">7.4.3</span> DNA words</h3>
<p>As well as the frequency of each of the individual nucleotides (“A,” “G,” “T,” “C”) in a DNA sequence, it is also interesting to know the frequency of longer <strong>DNA words</strong>, also referred to as <strong>genomic words</strong>. The individual nucleotides are DNA words that are 1 nucleotide long, but we may also want to find out the frequency of DNA words that are 2 nucleotides long (ie. “AA,” “AG,” “AC,” “AT,” “CA,” “CG,” “CC,” “CT,” “GA,” “GG,” “GC,” “GT,” “TA,” “TG,” “TC,” and “TT”), 3 nucleotides long (eg. “AAA,” “AAT,” “ACG,” etc.), 4 nucleotides long, etc.</p>
<p>To find the number of occurrences of DNA words of a particular length, we can use the count() function from the R SeqinR package.</p>
<p>The count() function only works with lower-case letters, so first we have to use the tolower() function to convert our upper class genome to lower case</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="dna-descriptive-statics-part-1.html#cb74-1" aria-hidden="true" tabindex="-1"></a>dengueseq_vector <span class="ot">&lt;-</span><span class="fu">tolower</span>(dengueseq_vector)</span></code></pre></div>
<p>Now we can look for words. For example, to find the number of occurrences of DNA words that are 1 nucleotide long in the sequence dengueseq_vector, we type:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="dna-descriptive-statics-part-1.html#cb75-1" aria-hidden="true" tabindex="-1"></a>seqinr<span class="sc">::</span><span class="fu">count</span>(dengueseq_vector, <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
##    a    c    g    t 
## 3426 2240 2770 2299</code></pre>
<p>As expected, this gives us the number of occurrences of the individual nucleotides. To find the number of occurrences of DNA words that are 2 nucleotides long, we type:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="dna-descriptive-statics-part-1.html#cb77-1" aria-hidden="true" tabindex="-1"></a>seqinr<span class="sc">::</span><span class="fu">count</span>(dengueseq_vector, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## 
##   aa   ac   ag   at   ca   cc   cg   ct   ga   gc   gg   gt   ta   tc   tg   tt 
## 1108  720  890  708  901  523  261  555  976  500  787  507  440  497  832  529</code></pre>
<p>Note that by default the count() function includes all overlapping DNA words in a sequence. Therefore, for example, the sequence “ATG” is considered to contain two words that are two nucleotides long: “AT” and “TG.”</p>
<p>If you type help(‘count’), you will see that the result (output) of the function count() is a table object. This means that you can use double square brackets to extract the values of elements from the table. For example, to extract the value of the third element (the number of Gs in the DEN-1 Dengue virus sequence), you can type:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="dna-descriptive-statics-part-1.html#cb79-1" aria-hidden="true" tabindex="-1"></a>denguetable_2 <span class="ot">&lt;-</span> seqinr<span class="sc">::</span><span class="fu">count</span>(dengueseq_vector,<span class="dv">2</span>)</span>
<span id="cb79-2"><a href="dna-descriptive-statics-part-1.html#cb79-2" aria-hidden="true" tabindex="-1"></a>denguetable_2[[<span class="dv">3</span>]]</span></code></pre></div>
<pre><code>## [1] 890</code></pre>
<p>The command above extracts the third element of the table produced by count(dengueseq_vector,1), which we have stored in the table variable denguetable.</p>
<p>Alternatively, you can find the value of the element of the table in column “g” by typing:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="dna-descriptive-statics-part-1.html#cb81-1" aria-hidden="true" tabindex="-1"></a>denguetable_2[[<span class="st">&quot;aa&quot;</span>]]</span></code></pre></div>
<pre><code>## [1] 1108</code></pre>
<p>Once you have table you can make a basic plot</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="dna-descriptive-statics-part-1.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(denguetable_2)</span></code></pre></div>
<p><img src="lbrb_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>We can sort by the number of words using the sort() command</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="dna-descriptive-statics-part-1.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(denguetable_2)</span></code></pre></div>
<pre><code>## 
##   cg   ta   tc   gc   gt   cc   tt   ct   at   ac   gg   tg   ag   ca   ga   aa 
##  261  440  497  500  507  523  529  555  708  720  787  832  890  901  976 1108</code></pre>
<p>Let’s save over the original object</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="dna-descriptive-statics-part-1.html#cb86-1" aria-hidden="true" tabindex="-1"></a>denguetable_2 <span class="ot">&lt;-</span> <span class="fu">sort</span>(denguetable_2)</span></code></pre></div>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="dna-descriptive-statics-part-1.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(denguetable_2)</span></code></pre></div>
<p><img src="lbrb_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>R will automatically try to optimize the appearance of the labels on the graph so you may not see all of them; no worries.</p>
<p>R can also make pie charts. Piecharts only really work when there are a few items being plots, like the four bases.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="dna-descriptive-statics-part-1.html#cb88-1" aria-hidden="true" tabindex="-1"></a>denguetable_1 <span class="ot">&lt;-</span> seqinr<span class="sc">::</span><span class="fu">count</span>(dengueseq_vector,<span class="dv">1</span>)</span></code></pre></div>
<p>Make a piechart with pie()</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="dna-descriptive-statics-part-1.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(denguetable_1)</span></code></pre></div>
<p><img src="lbrb_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
</div>
<div id="summary" class="section level3" number="7.4.4">
<h3><span class="header-section-number">7.4.4</span> Summary</h3>
<p>In this practical, have learned to use the following R functions:</p>
<p>length() for finding the length of a vector or list
table() for printing out a table of the number of occurrences of each type of item in a vector or list.
These functions belong to the standard installation of R.</p>
<p>You have also learnt the following R functions that belong to the SeqinR package:</p>
<p>GC() for calculating the GC content for a DNA sequence
count() for calculating the number of occurrences of DNA words of a particular length in a DNA sequence</p>
</div>
</div>
<div id="acknowledgements" class="section level2" number="7.5">
<h2><span class="header-section-number">7.5</span> Acknowledgements</h2>
<p>This is a modification of <a href="https://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/src/chapter1.html">“DNA Sequence Statistics (1)”</a> from Avril Coghlan’s <a href="https://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/index.html"><em>A little book of R for bioinformatics.</em></a>. Almost all of text and code was originally written by Dr. Coghlan and distributed under the <a href="https://creativecommons.org/licenses/by/3.0/us/">Creative Commons 3.0</a> license.</p>
<p>In “A little book…” Coghlan noted: “Many of the ideas for the examples and exercises for this chapter were inspired by the Matlab case studies on Haemophilus influenzae (www.computational-genomics.net/case_studies/haemophilus_demo.html) and Bacteriophage lambda (<a href="http://www.computational-genomics.net/case_studies/lambdaphage_demo.html" class="uri">http://www.computational-genomics.net/case_studies/lambdaphage_demo.html</a>) from the website that accompanies the book Introduction to Computational Genomics: a case studies approach by Cristianini and Hahn (Cambridge University Press; www.computational-genomics.net/book/).”</p>
<div id="license" class="section level3" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> License</h3>
<p>The content in this book is licensed under a Creative Commons Attribution 3.0 License.</p>
<p><a href="https://creativecommons.org/licenses/by/3.0/us/" class="uri">https://creativecommons.org/licenses/by/3.0/us/</a></p>
</div>
<div id="exercises" class="section level3" number="7.5.2">
<h3><span class="header-section-number">7.5.2</span> Exercises</h3>
<p>Answer the following questions, using the R package. For each question, please record your answer, and what you typed into R to get this answer.</p>
<p>Model answers to the exercises are given in Answers to the exercises on DNA Sequence Statistics (1).</p>
<ol style="list-style-type: decimal">
<li>What are the last twenty nucleotides of the Dengue virus genome sequence?</li>
<li>What is the length in nucleotides of the genome sequence for the bacterium Mycobacterium leprae strain TN (accession NC_002677)?
Note: Mycobacterium leprae is a bacterium that is responsible for causing leprosy, which is classified by the WHO as a neglected tropical disease. As the genome sequence is a DNA sequence, if you are retrieving its sequence via the NCBI website, you will need to look for it in the NCBI Nucleotide database.</li>
<li>How many of each of the four nucleotides A, C, T and G, and any other symbols, are there in the Mycobacterium leprae TN genome sequence?
Note: other symbols apart from the four nucleotides A/C/T/G may appear in a sequence. They correspond to positions in the sequence that are are not clearly one base or another and they are due, for example, to sequencing uncertainties. or example, the symbol ‘N’ means ‘aNy base,’ while ‘R’ means ‘A or G’ (puRine). There is a table of symbols at www.bioinformatics.org/sms/iupac.html.</li>
<li>What is the GC content of the <em>Mycobacterium leprae TN</em> genome sequence, when (i) all non-A/C/T/G nucleotides are included, (ii) non-A/C/T/G nucleotides are discarded?
Hint: look at the help page for the GC() function to find out how it deals with non-A/C/T/G nucleotides.</li>
<li>How many of each of the four nucleotides A, C, T and G are there in the complement of the Mycobacterium leprae TN genome sequence? <em>Hint</em>: you will first need to search for a function to calculate the complement of a sequence. Once you have found out what function to use, remember to use the help() function to find out what are the arguments (inputs) and results (outputs) of that function. How does the function deal with symbols other than the four nucleotides A, C, T and G? Are the numbers of As, Cs, Ts, and Gs in the complementary sequence what you would expect?</li>
<li>How many occurrences of the DNA words CC, CG and GC occur in the Mycobacterium leprae TN genome sequence?</li>
<li>How many occurrences of the DNA words CC, CG and GC occur in the (i) first 1000 and (ii) last 1000 nucleotides of the Mycobacterium leprae TN genome sequence?
1.How can you check that the subsequence that you have looked at is 1000 nucleotides long?</li>
</ol>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="downloading-ncbi-sequence-data-by-hand.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="downloading-dna-sequences-with-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["lbrb.pdf", "lbrb.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
