---
title: "UPGMA functions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{UPGMA functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r  eval = T}
library(compbio4all)
```


## Data 

```{r}
# The data
#      a   b   c   d   e
a <- c(0,	 17, 21, 31, 23)
b <- c(17, 0,	 30, 34, 21)
c	<- c(21, 30, 0,  28, 39)
d	<- c(31, 34, 28,	0, 43)
e	<- c(23, 21, 39, 43,	0)

# Bind into a matrix
dmat1 <- rbind(a,b,c,d,e)

# names
colnames(dmat1) <- c("a","b","c","d","e")

#set off diag to NA
diag(dmat1) <- NA
#dmat1[upper.tri(dmat1)] <- NA

n.taxa <- 5
```


## Data frame for storage

```{r}
UPGMA_output <- data.frame(it = c(1:c(n.taxa-1)),
                           clust.i = NA,
                           clust.j = NA,
                           dist.ij = NA,
                           clade.u = NA,
                           branch.l.ij = NA)
```



### Determine minimum value in current matrix

```{r}
cluster_taxa <- function(dmat){

  #The minimum distance
  dist.min.n <- min(dmat, na.rm = T)  
  
  
  #The index value of the minimum
  index.min.n <- which(dmat == dist.min.n, arr.ind =T)
  index.row.n <- index.min.n[1]
  index.col.n <- index.min.n[2]

  #names of the clusters
  cluster.j <- rownames(dmat)[index.row.n]
  cluster.i <- colnames(dmat)[index.col.n]
  
  #name of new cluster/clade
  clade.u <- paste(cluster.i,cluster.j, sep = "")

  #branch length
  branch.l.ij <- dist.min.n/2
  
  cluster_output <- c(cluster.i,cluster.j,dist.min.n,clade.u,branch.l.ij)
  
  names(cluster_output) <- c("clust.i","clust.j","dist.ij","clade.u","branch.l.ij")
  
  return(cluster_output)
}
```


```{r}
cluster_output <- cluster_taxa(dmat1)

UPGMA_output[1,c("clust.i","clust.j","dist.ij","clade.u","branch.l.ij")] <- cluster_output
```



### Calculate distance from clade to all other points

```{r}
recalculate_distance <- function(dmat, cluster_output){

#make a new matrix
## get names from current matrix
clusters <- colnames(dmat)
i <- which(clusters == cluster_output["clust.i"])
j <- which(clusters == cluster_output["clust.j"])

#make dummy matrix
newmat <- dmat

#turn taxa that were clustered to NA
newmat[c(i,j),  ] <- NA
newmat[      ,  c(i,j  ) ] <- NA


# #reorganize clustered taxa to be on far left of matrix
# newmat <- cbind(newmat[      ,c(i,j)],
#                 newmat[      ,-c(i,j)])
# 
# 
# #reorganize clustered taxa to be on far top of matrix
# newmat <- rbind(newmat[c(i,j), ],
#                 newmat[-c(i,j), ])

#rename empty column/row with clade name
colnames(newmat)[i] <- cluster_output["clade.u"]
rownames(newmat)[j] <- cluster_output["clade.u"]

#remove one column and one row
newmat <- newmat[-i, ]
newmat <- newmat[ ,-j ]


#make vector of taxa that weren't in the pair clustered
clusters.no.ij <- clusters[-c(i,j)]

# loop over the taxa names
## calcualte distance from new clade to remaining taxa

for(t in 1:length(clusters.no.ij)){
  
  # taxa k to recompute distance to
  cluster.k <- clusters.no.ij[t]
  
  # distance i to k
  d.ik <- dmat[cluster.k, cluster_output["clust.i"]]
  
  #distance j to k
  d.jk <- dmat[cluster.k, cluster_output["clust.j"]]
  
  # Calculate cluster size
  ## ...
  T.i  <- 1
  T.j  <- 1
  
  # calculate new distance
  d.ku <- (T.i*d.ik + T.j*d.jk)/(T.i + T.j)
  
  # add new distance to new matrix
  newmat[cluster.k,cluster_output["clade.u"]] <- d.ku
  newmat[cluster_output["clade.u"],cluster.k] <- d.ku
  
}

return(newmat)
  
}


dmat2 <- recalculate_distance(dmat = dmat1, cluster_output)
  
```



```{r}
UPGMA_output <- data.frame(it = c(1:c(n.taxa-1)),
                           clust.i = NA,
                           clust.j = NA,
                           dist.ij = NA,
                           clade.u = NA,
                           branch.l.ij = NA)

cluster_output1 <- cluster_taxa(dmat1)

UPGMA_output[i,c("clust.i","clust.j","dist.ij","clade.u","branch.l.ij")] <- cluster_output1

dmat2 <- recalculate_distance(dmat = dmat1, cluster_output1)
```


```{r}
cluster_output2 <- cluster_taxa(dmat2)

UPGMA_output[2,c("clust.i","clust.j","dist.ij","clade.u","branch.l.ij")] <- cluster_output2

#debugonce(recalculate_distance)
dmat3 <- recalculate_distance(dmat = dmat2, cluster_output2)
```


TODO doesn't work
```{r eval = F}
cluster_output3 <- cluster_taxa(dmat3)

UPGMA_output[3,c("clust.i","clust.j","dist.ij","clade.u","branch.l.ij")] <- cluster_output3

#debugonce(recalculate_distance)
dmat4 <- recalculate_distance(dmat = dmat3, cluster_output3)
```

```{r}

```

