---
title: "Simulating normal data"
author: "Nathan Brouwer"
date: "10/11/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##


Williams et al. A randomized placebo‑controlled trial to investigate the effect
of lactolycopene on semen quality in healthy males. European Journal of Nutrition.


Fast Progressive

```{r}
x.beta<-seq(from = 0,to = 1,by=0.01)
d.beta.fp <- dbeta(x = x.beta,shape2=20, shape1= 2)
plot(x = x.beta,y= d.beta.fp,type = "l")
```

```{r}
b <- rbinom(n = n, size = 200,prob = mean.fp/100)/200
mean(b)
sd(b)
```






```{r}

n.trt       <- 28
mean.fp.base <- 10.6
sd.fp.base   <- 8.57
se.fp.base   <- sd.fp.base/sqrt(n.trt)
ci95.fp.base <- 1.96*se.fp.base

x.fp.base <- seq(from = c(mean.fp.base-3*sd.fp.base),to = c(mean.fp.base+3*sd.fp.base),by = 0.1)

d.norm.fp.base <- dnorm(x = x.fp.base,
                        mean= mean.fp.base, 
                        sd= sd.fp.base)

plot(x = x.fp.base,y =d.norm.fp.base, type = "l")

points(x = mean.fp.base, y = 0.02,pch = 2)
segments(x0 = mean.fp.base-ci95.fp.base,
         x1 = mean.fp.base+ci95.fp.base,
         y0= 0.02, y1= 0.02)
abline(v = 0, lwd = 10)
```



```{r}
# how long to search for optimum
loops <- 20000

# storage matrix
data.summary.base <- matrix(data = NA,
          nrow = loops,
          ncol = n.trt)
data.summary.base <- data.frame(data.summary.base)


#loop
for(i in 1:loops){
  # generate random data

rand.trt.base <- rnorm(n = n.trt,
      mean = mean.fp.base,
      sd= sd.fp.base)

#make sure all values > 0
while(any(rand.trt.base< 0) == TRUE){
  i.0 <- which(rand.trt.base < 0)
  rand.trt.base[i.0] <- rnorm(n = length(i.0),
                              mean = mean.fp.base,
                              sd   = sd.fp.base)
  }

data.summary.base[i,] <- rand.trt.base

  
}



```


```{r}
base.mean <- apply(data.summary.base,1,mean)
base.sd <- apply(data.summary.base,1,sd)
e.mean <- abs(base.mean - mean.fp.base) #10.55-10.64
e.sd <- abs(base.sd - sd.fp.base)

data.base.summary <- data.frame(base.mean,
                                base.sd,
                                e.mean,
                                e.sd)

```

```{r}
plot(base.mean ~ base.sd)
abline(v= sd.fp.base, col = 2)
abline(h= mean.fp.base, col =2)
abline(v= sd.fp.base+0.25, col = 2)
abline(v= sd.fp.base-0.25, col = 2)
abline(h= mean.fp.base, col =2)
abline(h= mean.fp.base+0.25, col =2)
abline(h= mean.fp.base-0.25, col =2)
```


```{r}
i.hit.base <-which(e.mean < 0.25 & 
        e.sd < 0.25)

data.base.summary[i.hit.base, ]

hist(t(data.summary.base[i.hit.base[3],-c(1:4)]))

data.base.hits <- data.summary.base[i.hit.base, ]
```


```{r}
data.base.hits[1,]
n.its <- 1000000
seed.out <- matrix(data = NA, ncol = n.its+1, nrow = n.trt)

seed.out[,1] <- t(data.base.hits[1,])
scale. <- 0.05
x.lim <- c(mean(seed.out[,1])-mean(seed.out[,1])*scale.,
                  mean(seed.out[,1]+ mean(seed.out[,1])*scale.))
y.lim <- c(sd(seed.out[,1])-sd(seed.out[,1])*scale.,
           sd(seed.out[,1]) + sd(seed.out[,1]*scale.))

plot(mean(seed.out[,1]) , sd(seed.out[,1]), 
       xlim = x.lim,
       ylim = y.lim,pch =3)
points(mean.fp.base , sd.fp.base,pch =2, col =2)

    

noise <-0.1
for(i in 1:n.its){
  #print index
 # print(i)
  
  #take current best hit
  ## calculate summary stats
  seed.ij.1 <- seed.out[,1]
  mean.ij.1 <- mean(seed.ij.1)
  sd.ij.1   <- sd(seed.ij.1)
  
  #calculate current distnace
  dist.1 <- sqrt((mean.fp.base-mean.ij.1)^2 + (sd.fp.base-sd.ij.1)^2)
 
  
  # add noise
  seed.ij.2 <- seed.ij.1 + runif(n = n.trt, min = -noise, max = noise)
  
  #calcualte new summary stats
  mean.ij.2 <- mean(seed.ij.2)
  sd.ij.2   <- sd(seed.ij.2)
  
  dist.2 <- sqrt((mean.fp.base-mean.ij.2)^2 + (sd.fp.base-sd.ij.2)^2)
 
  
  while(abs(mean.fp.base-mean.ij.1) < abs(mean.fp.base-mean.ij.2) &
        abs(  sd.fp.base  -sd.ij.1) < abs(  sd.fp.base-  sd.ij.2)){
        
       seed.ij.2 <- seed.ij.1 +runif(n = n.trt, min = -noise, max = noise)
       mean.ij.2 <- mean(seed.ij.2)
       sd.ij.2   <- sd(seed.ij.2)
  
  }
  #points(mean.ij.2, sd.ij.2,col =i)
  seed.out[,i+1] <- seed.ij.2

}
 


means. <- apply(seed.out,2,mean)
sd. <- apply(seed.out,2,sd)

points(means.,sd.)

```




```{r}

```

```{r}
dim(data.base.hits)
dim(data.wk12.hits)
```


```{r}
p.out <- matrix(data = NA, nrow = nrow(data.base.hits), ncol = nrow(data.wk12.hits))

for(i in 1:nrow(data.base.hits)){
  for(j in 1:nrow(data.wk12.hits)){
    base. <- (data.base.hits[i,-c(1:4)])
  wk.12 <- (data.wk12.hits[j,-c(1:4)])
  #plot(t(base.), t(wk.12))
  p.ij <- t.test(t(base.),
                t(wk.12),
          paired = T)$p.value
  p.out[i,j] <- p.ij
  # print(p.ij)
  # print(i)
  # print(j)
  # cat("\n\n")
  }
  
}

which(p.out < 0.00651 & p.out > 0.00551)

min(p.out)

```


```{r}
i <- 7
j <- 4
  base. <- t(data.base.hits[i,-c(1:4)])
  wk.12 <- t(data.summary.wk12[j,-c(1:4)])
  t.test(base., wk.12,paired = T)
plot(base., wk.12)
```



