---
title: "Untitled"
author: "Nathan Brouwer"
date: "10/11/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##


Williams et al. A randomized placebo‑controlled trial to investigate the effect
of lactolycopene on semen quality in healthy males. European Journal of Nutrition.


Fast Progressive

```{r}
x.beta<-seq(from = 0,to = 1,by=0.01)
d.beta.fp <- dbeta(x = x.beta,shape2=20, shape1= 2)
plot(x = x.beta,y= d.beta.fp,type = "l")
```

```{r}
b <- rbinom(n = n, size = 200,prob = mean.fp/100)/200
mean(b)
sd(b)
```




## Fast- progressive baseline

```{r}

n.trt       <- 28
mean.fp.base <- 10.6
sd.fp.base   <- 8.57
se.fp.base   <- sd.fp.base/sqrt(n.trt)
ci95.fp.base <- 1.96*se.fp.base

x.fp.base <- seq(from = c(mean.fp.base-3*sd.fp.base),to = c(mean.fp.base+3*sd.fp.base),by = 0.1)

d.norm.fp.base <- dnorm(x = x.fp.base,
                        mean= mean.fp.base, 
                        sd= sd.fp.base)

plot(x = x.fp.base,y =d.norm.fp.base, type = "l")

points(x = mean.fp.base, y = 0.02,pch = 2)
segments(x0 = mean.fp.base-ci95.fp.base,
         x1 = mean.fp.base+ci95.fp.base,
         y0= 0.02, y1= 0.02)
abline(v = 0, lwd = 10)
```


## Fast-progressive 12 weeks


```{r}

n.trt       <- 28
mean.fp.wk12 <- 14.76
sd.fp.wk12   <- 10.29
se.fp.wk12   <- sd.fp.wk12/sqrt(n.trt)
ci95.fp.wk12 <- 1.96*se.fp.wk12

x.fp.wk12 <- seq(from = c(mean.fp.wk12-3*sd.fp.wk12),to = c(mean.fp.wk12+3*sd.fp.wk12),by = 0.1)

d.norm.fp.wk12 <- dnorm(x = x.fp.wk12,
                        mean= mean.fp.wk12, 
                        sd= sd.fp.wk12)

plot(x = x.fp.wk12,y =d.norm.fp.wk12, type = "l")

points(x = mean.fp.wk12, y = 0.02,pch = 2)
segments(x0 = mean.fp.wk12-ci95.fp.wk12,
         x1 = mean.fp.wk12+ci95.fp.wk12,
         y0= 0.02, y1= 0.02)
abline(v = 0, lwd = 10)
```

## Find hit

```{r}
base.hits <- find_hits(n.its = 500000, n = n.trt, 
                       target.mean = mean.fp.base, target.sd = sd.fp.base,
                       tolerance.mean = 0.25, tolerance.sd = 0.25)
```


```{r}
wk12.hits <- find_hits(n.its = 500000, n = n.trt, 
                       target.mean = mean.fp.wk12, target.sd =sd.fp.wk12,
                       tolerance.mean = 0.125, tolerance.sd = 0.125)
```

## Optimize hits


baseline

```{r}
opt.hit.list.base <- list(NA)

for(h in 1:nrow(base.hits)){
  opt.hit.list.base[[h]] <- optimize_hit(hit = t(base.hits[h,]),
                                    n.its = 1000,
                                    target.mean = mean.fp.base,
                                    target.sd =   sd.fp.base,
                                    tolerance.mean = 0.05,
                                    tolerance.sd = 0.005,
                                    n = n.trt)
}

```


```{r}
opt.hit.list.wk12 <- list(NA)

for(h in 1:nrow(wk12.hits)){
  opt.hit.list.wk12[[h]] <- optimize_hit(hit = t(wk12.hits[h,]),
                                    n.its = 1000,
                                    n = n.trt,
                                    target.mean = mean.fp.wk12,
                                    target.sd =   sd.fp.wk12,
                                    tolerance.mean = 0.075,
                                    tolerance.sd = 0.0085)
}

```


```{r}
# mean(sort(opt.hit.list.base[[1]][,1]))
# mean(sort(opt.hit.list.base[[2]][,1]))
# mean(sort(opt.hit.list.base[[3]][,1]))
# 
# 
# mean(sort(opt.hit.list.wk12[[1]][,1]))
# mean(sort(opt.hit.list.wk12[[2]][,1]))
# mean(sort(opt.hit.list.wk12[[3]][,1]))
# 
# t.test((opt.hit.list.base[[1]][,1]),
#        (opt.hit.list.wk12[[1]][,1]))
```


```{r}
n.hits.base <- length(opt.hit.list.base)
n.hits.wk12 <- length(opt.hit.list.wk12)

p.matrix <- matrix(data = NA, 
                   nrow = n.hits.base,
                   ncol = n.hits.wk12)
dim(p.matrix)
p.target <- 0.006

for(i in 1:nrow(p.matrix)){
  for(j in 1:ncol(p.matrix)){

    
    if(is.matrix(opt.hit.list.base[[i]])== FALSE){
      base <- opt.hit.list.base[[i]]
    }else{
      base <- opt.hit.list.base[[i]][,1]
    }
    
    if(is.matrix(opt.hit.list.wk12[[j]])== FALSE){
      wk12 <- opt.hit.list.wk12[[j]]
    }else{
      wk12 <- opt.hit.list.wk12[[j]][,1]
    }
    
    p.matrix[i,j] <- t.test(base, wk12,paired = T)$p.value
  }
}

min(p.matrix)
save.image(file = "run2.RData")

```



```{r}

```




```{r}

```

