---
title: "Untitled"
author: "Nathan Brouwer"
date: "10/24/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 


source?


```{r}
seq1 <- "GCATGCU"
seq2 <- "GATTACA"

seq1.vect <- unlist(strsplit(seq1,""))
seq2.vect <- unlist(strsplit(seq2,""))

seq1.vect <- c("",seq1.vect)
seq2.vect <- c("",seq2.vect)

n.col <- length(seq1.vect)
n.row <- length(seq2.vect)

mat <- matrix(data = NA, ncol = n.col, nrow = n.row)

colnames(mat) <- seq1.vect
rownames(mat) <- seq2.vect

mat[1, ] <- -1*seq(from = 0,to = n.col-1,by= 1)
mat[,1 ] <- -1*seq(from = 0,to = n.row-1,by= 1)

m.atch <- 1
mis.ma <- -1
indel  <- -1


mat2 <- mat


```


```{r}
j <-2
i <-2
```

```{r}
alingner.out <- aligner(seq1 = seq1.vect, seq2 = seq2.vect)
```

```{r}
which.max(c(1,1,0))
```

```{r}
aligner <- function(seq1, seq2){
  for(i in 2:nrow(mat)){
  for(j in 2:ncol(mat)){
    s1.j <- seq1[j]
    s2.i <- seq2[i]
    
    #down
    down <- indel + mat[i-1,j]
    
    #Diagonal
    if(s1.j == s2.i){diag <- m.atch + mat[i-1,j-1]}
    if(s1.j != s2.i){diag <- mis.ma + mat[i-1,j-1]}
    
    #right
    right <- indel + mat[i,j-1]
    
    cumulative.ij    <- max(c(down,diag,right))
    arrows.ij        <- which(c(down,diag,right) == max(c(down,diag,right) ))
    mat[i,j]  <- cumulative.ij
    mat2[i,j] <- paste(arrows.ij,sep = "",collapse = ",")
    
  }
  }
  
  return(list(mat,mat2))
}




```


```{r}
i <- 8
j <- 8

alignment <- rbind(NA,NA)

mat.arrows <- alingner.out[[2]]

max.ij <- c(8,8)


next.ij <- c(8,8)

#use while()
  
trace_back<- function(){
  for(i in max.ij[1]:1){
    if(i <max.ij[1] & next.ij[1] != i){next}
  
    for(j in max.ij[2]:1){
    
    if(j <max.ij[2] & next.ij[2] != j){next}
    
    if(mat.arrows[i,i] == "1"){
      next.residues <- rbind(seq1.vect[i],seq1.vect[j])
      next.ij <- c(i-1,j)
      }
    if(mat.arrows[i,i]=="2"){
      next.residues <- rbind("-",seq1.vect[j])
      next.ij <- c(i-1,j-1)
      }
    if(mat.arrows[i,i]=="3"){
      next.residues <- rbind(seq1.vect[i],"-")
      next.ij <- c(i,j-1)
      }
    alignment<-cbind(next.residues,alignment)
  }
  }
  
  return(alignment)

}




```

