---
title: "T-test example"
author: "Nathan Brouwer"
date: "10/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## R Markdown


A table of amino acids and their frequencies
```{r}
frequencies <- c(0.089, 0.087, 0.085, 0.081, 0.070, 
                 0.065, 0.058, 0.051, 0.050, 0.047, 
                 0.041, 0.040, 0.040, 0.038, 0.037, 
                 0.034, 0.033, 0.030, 0.015, 0.010)

aa3 <- c("Gly","Ala","Leu","Lys","Ser", 
         "Val","Thr","Pro","Glu","Asp",
         "Arg","Asn","Phe","Gln","Ile",
         "His","Cys","Tyr","Met","Trp")

aa <- c("G", "A", "L", "K", "S", 
        "V", "T", "P", "E", "D",
        "R", "N", "F", "Q", "I",
        "H", "C", "Y", "M", "W")

freqs <- data.frame(aa3 = aa3[order(aa3)], 
                    aa  = aa[order(aa3)],
                    frequencies = frequencies[order(aa3)],
                    stringsAsFactors = F)

```

A function to generate random sequences

```{r}
rand_seq_aa <- function(n = 100, aas, probs){
   sample(x = aas, 
          size = n, 
          replace = TRUE, 
          prob = probs)
}


```


```{r}
n.seq <- 5
list.names <- paste("randseq",1:n.seq,sep = "")
blast.output <- as.list(list.names)
names(blast.output) <- list.names
for(i in 1:length(blast.output)){
  rand.seq <-  rand_seq_aa(n = 100, aas = freqs$aa, probs = freqs$frequencies)
  
  blast.output[[i]] <- blastr(seq = rand.seq, maxhits = 2)$hit.tbl
}
```



Generate a random sequence
```{r}
rand1 <- rand_seq_aa(n = 100, aas = freqs$aa, probs = freqs$frequencies)

rand2 <- rand_seq_aa(n = 100, aas = freqs$aa, probs = freqs$frequencies)

rand3 <- rand_seq_aa(n = 100, aas = freqs$aa, probs = freqs$frequencies)
rand4 <- rand_seq_aa(n = 100, aas = freqs$aa, probs = freqs$frequencies)
rand5 <- rand_seq_aa(n = 100, aas = freqs$aa, probs = freqs$frequencies)
rand6 <- rand_seq_aa(n = 100, aas = freqs$aa, probs = freqs$frequencies)




```


```{r}
rand1.unif <- rand_seq_aa(n = 100, aas = freqs$aa, probs = rep(1,length(freqs$aa)))

rand2.unif <- rand_seq_aa(n = 100, aas = freqs$aa, probs = rep(1,length(freqs$aa)))

rand3.unif <- rand_seq_aa(n = 100, aas = freqs$aa, probs = rep(1,length(freqs$aa)))


rand4.unif <- rand_seq_aa(n = 100, aas = freqs$aa, probs = rep(1,length(freqs$aa)))

rand5.unif <- rand_seq_aa(n = 100, aas = freqs$aa, probs = rep(1,length(freqs$aa)))

rand6.unif <- rand_seq_aa(n = 100, aas = freqs$aa, probs = rep(1,length(freqs$aa)))
rand7.unif <- rand_seq_aa(n = 100, aas = freqs$aa, probs = rep(1,length(freqs$aa)))

```

BLAST the random sequence

```{r}
#install.packages("bio3d")
library(bio3d)

rand1.blast <- blastr(seq = rand1, maxhits = 2)
rand2.blast <- blastr(seq = rand2, maxhits = 2)

rand3.blast <- blastr(seq = rand3, maxhits = 2)
rand4.blast <- blastr(seq = rand4, maxhits = 2)
rand5.blast <- blastr(seq = rand5, maxhits = 2)
rand6.blast <- blastr(seq = rand6, maxhits = 2)
```


```{r}
rand <-rbind(rand1.blast$hit.tbl[1,],
rand2.blast$hit.tbl[1,],
rand3.blast$hit.tbl[1,],
rand4.blast$hit.tbl[1,],
rand5.blast$hit.tbl[1,],
rand6.blast$hit.tbl[1,])
```


```{r}
rand1.unif.blast <- blastr(seq = rand1.unif, maxhits = 2)
rand2.unif.blast <- blastr(seq = rand2.unif, maxhits = 2)
rand3.unif.blast <- blastr(seq = rand3.unif, maxhits = 2)


rand4.unif.blast <- blastr(seq = rand4.unif, maxhits = 2)

rand5.unif.blast <- blastr(seq = rand5.unif, maxhits = 2)

rand6.unif.blast <- blastr(seq = rand6.unif, maxhits = 2)
rand7.unif.blast <- blastr(seq = rand7.unif, maxhits = 2)

rand.unif <- rbind(rand1.unif.blast$hit.tbl[1,],
rand2.unif.blast$hit.tbl[1,],
rand3.unif.blast$hit.tbl[1,],
rand4.unif.blast$hit.tbl[1,],
rand5.unif.blast$hit.tbl[1,],
rand6.unif.blast$hit.tbl[1,])



```


```{r}
t.test(rand$identity,rand.unif$identity)
```

