---
title: "Untitled"
author: "Nathan Brouwer"
date: "10/15/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

We'll consider the second to last column, under "Week 12"

What is +/- X mean?
What type of number is after the +/-?  
What is the sample size?


```{r}

n <- 28
my.mean <- 14.76
my.sd   <- 10.29

my.data <- rnorm(n = n, mean = my.mean, sd = my.sd)



```

```{r}
mean(my.data)
sd(my.data)
```

```{r}
my.min <- 0
my.max <- 8*my.sd
```

```{r}
my.seq <- seq(from = my.min, to = my.max, by = 0.1)

min(my.seq)
max(my.seq)
range(my.seq)

my.norm.curve <- dnorm(x = my.seq, mean = my.mean, sd = my.sd)


```


```{r}
plot(my.norm.curve ~ my.seq, type = "l")
```

```{r}
hist(my.data)
```

Pseudo code:

sample size
range

1. Use mean, SD, N to simulate data from normal distribution
2. Which values are <0?
3. For non-zero values, make a new value
4. keep doing this until everything is consistent

```{r}
baseline <- c(2.165751, 18.595921,17.158801, 5.626549,1.907980,14.834630,1.568601,6.341502,18.489389,7.322593,9.938555,2.806024, 9.029434,29.948006, 2.247686,1.58033, 19.597228, 22.094942,  5.713589, 16.128858,  8.063147,  4.301943,  5.228189, 10.151284, 14.225289,  1.647791, 33.016771,  9.826562)

mean(baseline)
sd(baseline)

## week 12 - after 12 weeks of treament
wk.12 <-c(18.375663,  29.441635,   6.886321,   8.832303,  33.199704,  4.642406,  5.507830, 31.062378, 24.982074, 10.936893, 12.973502,  3.417660, 22.097952, 41.831826, 29.514890, 31.862180,  7.920042,  5.168505, 20.554914, 18.899862, 16.361024, 63.875732, 42.017015, 35.062467,  5.957915,  1.759863, 11.808719, 43.414362)

mean(wk.12)
sd(wk.12)
t.test(baseline,wk.12,paired = T)

```


```{r}
hist(wk.12)
```

```{r}
difference <- wk.12 - baseline
```


```{r}
hist(difference)
```

```{r}

t.test(arm::logit(difference))
```



```{r}
library(arm)
t.test((wk.12/100), (baseline/100),paired = T)
mean(wk.12/100)
mean(baseline/100)
mean(wk.12/100-baseline/100)
t.test(logit(wk.12/100), logit(baseline/100),paired = T)


mean(wk.12)
mean(baseline)
wilcox.test(wk.12,baseline,
            paired = TRUE)
```

```{r}
#baseline
x <- rnorm(n = n, mean = my.mean, sd = my.sd)

#follow up
y <- rnorm(n = n, mean = my.mean, sd = my.sd)

difference <- y - x

which(difference > 40)

t.test(difference[-40])
```

